open Utils;;
open Importer;;
open State_machine;;
(* Toggle test code *)

Random.self_init ()

(* Expected generation result: *)

let expected = Printf.sprintf "# Generated by graph2strat v%s by KirrimK@ENAC
# Report any issues on github: KirrimK/graph2strat
# Do not edit this auto-generated file manually
import typing

%s

# start of G2S machine
class G2S:
    def __init__(self, parent: typing.Any, debug=False):
        self.name = \"stm_Toggle\"
        self.parent = parent
        self.debug = debug
        self.started = False
        self.Init = State(\"Init\")
        self.Toggle = State(\"Toggle\")
        self.InitToToggle = Transition(\"InitToToggle\", self.Toggle)
        self.Init.add_transition(self.InitToToggle)
        self.ToggleToInit = Transition(\"ToggleToInit\", self.Init)
        self.Toggle.add_transition(self.ToggleToInit)
        self.stm_Toggle = StateMachine(self.Init)

    def __str__(self):
        return \"G2S (\" +str(self.name) + \") machine, internals: \" + str(self.stm_Toggle)

    def start(self):
        if self.started:
            print(\"G2S (\", self.name ,\") machine is already running\")
            return
        self.stm_Toggle.start()
        self.started = True
        if self.debug:
            print(\"Started running G2S (\", self.name ,\") machine, state is\", self.stm_Toggle.state)
    
    def check_transitions(self):
        if self.debug:
            print(\">> Checking transitions, state is\", self.stm_Toggle.state)
        self.stm_Toggle.check_transitions()
        if self.debug:
            print(\"<< Transitions checked, state is\", self.stm_Toggle.state)
" version lib;;

(* Create a random folder name *)
let folder = "/tmp/testg2s" ^ (string_of_int (Random.int 1000000))

(* Create folder *)
let _ = Sys.command ("mkdir " ^ folder)

(* Create a random file name *)
let file = "test" ^ (string_of_int (Random.int 1000000)) ^ ".dot"

(* Copy content of test_files/toggle.dot to random file *)
let _ = Sys.command ("cp ./test_files/toggle.dot " ^ folder ^ "/" ^ file)

(* Create a new graph from the random file *)
let input = read_file (folder^"/"^file)
let lexbuf = Lexing.from_string (input ^ "\n")
let stm = Parser.main Lexer.token lexbuf
let compiled = include_compile stm

let compiled_filename = path_add_name_suffix_change_extension "_g2s" "py" file

let oc = open_out (folder ^ "/" ^ compiled_filename)
let () = Printf.fprintf oc "%s" compiled
let () = close_out oc

(* Compare to expected result *)
let () = assert(expected = compiled)

(* Python execution test *)

(* Python script to run *)
let python_file = "test" ^ (string_of_int (Random.int 1000000)) ^ ".py"
let oc = open_out (folder ^ "/" ^ python_file)
let () = Printf.fprintf oc "
from %s import G2S

class Parent:
    def __init__(self):
        pass

parent = Parent()
stm = G2S(parent)
stm.debug = True
stm.start()
stm.check_transitions()
stm.check_transitions()
" (List.nth (String.split_on_char '.' compiled_filename) 0)
let () = close_out oc

(* Run python script *)

(* Expected stdout output *)
let expected_stdout = 
"Init: on_enter_default
Started running G2S ( stm_Toggle ) machine, state is State(Init, [Transition(InitToToggle) ])
>> Checking transitions, state is State(Init, [Transition(InitToToggle) ])
InitToToggle: accept_by_default
Init: on_leave_default
InitToToggle: nothing
Toggle: on_enter_default
<< Transitions checked, state is State(Toggle, [Transition(ToggleToInit) ])
>> Checking transitions, state is State(Toggle, [Transition(ToggleToInit) ])
ToggleToInit: accept_by_default
Toggle: on_leave_default
ToggleToInit: nothing
Init: on_enter_default
<< Transitions checked, state is State(Init, [Transition(InitToToggle) ])
"

(* Run python script *)
let _ = Sys.command ("python3 " ^ folder ^ "/" ^ python_file ^ " > " ^ folder ^ "/stdout.txt")

(* Read stdout output *)
let stdout = read_file (folder ^ "/stdout.txt")

(* Compare to expected stdout output *)
let () = assert(expected_stdout = stdout)

(* Remove folder *)
let _ = Sys.command ("rm -rf " ^ folder)

(* End of test code *)