name: Build on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: sudo chown -R $USER:$USER .

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      
      - name: make deb package
        run: cd packaging && sudo make deb
      
      - run: cd ..

      - name: Archive .deb package
        uses: actions/upload-artifact@v3
        with:
          name: graph2strat-static-${{ github.ref_name }}.deb
          path: ./_build/packaging/deb/graph2strat-static.deb
