name: Build on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: sudo chown -R $USER:$USER .
      
      - name: make deb package
        run: cd packaging/deb && sudo make
      
      - run: cd ../..

      - name: Archive .deb package
        uses: actions/upload-artifact@v3
        with:
          name: graph2strat-static-${{ github.ref_name }}.deb
          path: ./_build/packaging/deb/graph2strat-static.deb
